import { AnalysisResult } from '@/types/analysis';
import { jsPDF } from 'jspdf';

export function downloadJSON(analysis: AnalysisResult) {
  const filename = `ObjectLens_${analysis.objectName.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.json`;
  const jsonStr = JSON.stringify(analysis, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function copyAnalysisToClipboard(analysis: AnalysisResult): Promise<void> {
  const text = `
=== OBJECTLENS AI ANALYSIS REPORT ===
Object: ${analysis.objectName}
Category: ${analysis.category}
AI Overall Confidence: ${analysis.confidence}%
Condition: ${analysis.condition}

PHYSICAL PROPERTIES:
- Weight: ${analysis.estimatedWeight.value} ${analysis.estimatedWeight.unit} (${analysis.estimatedWeight.label || 'AI Estimated Weight'})
- Weight Confidence: ${analysis.estimatedWeight.confidence}%
- Dimensions: ${analysis.dimensions.length} × ${analysis.dimensions.width} × ${analysis.dimensions.height} ${analysis.dimensions.unit} [Source: ${analysis.dimensions.source}]
- Volume: ${analysis.estimatedVolume.value} ${analysis.estimatedVolume.unit}
- Density: ${analysis.estimatedDensity.value} ${analysis.estimatedDensity.unit}
- Material: ${analysis.material.primaryMaterial} (${analysis.material.texture}, ${analysis.material.reflectivity})
- Primary Color: ${analysis.color.primary} (${analysis.color.hex})

SCIENTIFIC ASSUMPTIONS:
${analysis.assumptions.map(a => `- ${a}`).join('\n')}

Generated by ObjectLens AI - https://objectlens.ai
`.trim();

  return navigator.clipboard.writeText(text);
}

export function generatePDFReport(analysis: AnalysisResult) {
  try {
    const doc = new jsPDF();
    const lineSpacing = 8;
    let y = 20;

    // Header
    doc.setFillColor(8, 11, 20);
    doc.rect(0, 0, 210, 30, 'F');

    doc.setTextColor(56, 189, 248);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('OBJECTLENS AI', 14, 18);

    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text('PHYSICAL OBJECT ANALYSIS REPORT', 14, 25);

    y = 40;

    // Overview Box
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, y, 182, 35, 3, 3, 'FD');

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(analysis.objectName, 20, y + 12);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(`Category: ${analysis.category}  |  Confidence: ${analysis.confidence}%  |  Date: ${new Date(analysis.timestamp).toLocaleDateString()}`, 20, y + 22);
    doc.text(`Condition: ${analysis.condition}`, 20, y + 29);

    y += 45;

    // Physical Properties Table
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Physical Characteristics', 14, y);
    y += 6;

    const props = [
      ['Estimated Weight', `${analysis.estimatedWeight.value} ${analysis.estimatedWeight.unit} (${analysis.estimatedWeight.confidence}% conf.)`, analysis.estimatedWeight.label || 'AI Estimate'],
      ['Dimensions (L×W×H)', `${analysis.dimensions.length} × ${analysis.dimensions.width} × ${analysis.dimensions.height} ${analysis.dimensions.unit}`, `Source: ${analysis.dimensions.source}`],
      ['Volume', `${analysis.estimatedVolume.value} ${analysis.estimatedVolume.unit}`, 'Volumetric calculation'],
      ['Density', `${analysis.estimatedDensity.value} ${analysis.estimatedDensity.unit}`, 'Material density matrix'],
      ['Material', `${analysis.material.primaryMaterial}`, `${analysis.material.texture}, ${analysis.material.reflectivity}`],
      ['Primary Color', `${analysis.color.primary} (${analysis.color.hex})`, `RGB: ${analysis.color.rgb}`],
      ['Shape', analysis.shape, 'Visual geometry']
    ];

    doc.setFontSize(9);
    props.forEach(([label, val, note]) => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(51, 65, 85);
      doc.text(label, 14, y);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(15, 23, 42);
      doc.text(val, 70, y);

      doc.setTextColor(100, 116, 139);
      doc.text(note, 140, y);

      doc.setDrawColor(241, 245, 249);
      doc.line(14, y + 2, 196, y + 2);
      y += lineSpacing;
    });

    y += 6;

    // Scientific Notice Box
    doc.setFillColor(254, 243, 199);
    doc.setDrawColor(251, 191, 36);
    doc.roundedRect(14, y, 182, 24, 2, 2, 'FD');

    doc.setTextColor(180, 83, 9);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Scientific Limitation & Weight Disclosure:', 18, y + 7);
    doc.setFont('helvetica', 'normal');
    doc.text('Camera vision cannot directly weigh objects without a connected sensor. Weight shown is an AI estimate', 18, y + 13);
    doc.text('derived from estimated volume, shape, and material density assumptions.', 18, y + 18);

    y += 32;

    // Assumptions Section
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('AI Physical Assumptions:', 14, y);
    y += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    analysis.assumptions.forEach(assump => {
      const splitText = doc.splitTextToSize(`• ${assump}`, 180);
      doc.text(splitText, 14, y);
      y += splitText.length * 5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('ObjectLens AI Report • Generated autonomously by ObjectLens Multimodal Vision Engine', 14, 285);

    const safeName = analysis.objectName.replace(/[^a-z0-9]/gi, '_');
    doc.save(`ObjectLens_${safeName}_Report.pdf`);
  } catch (err) {
    console.error('PDF Generation failed:', err);
    alert('PDF export failed. You can copy the text report or download JSON.');
  }
}
